/* PURA offline worker pura-stable-d5636267f962 — generated by the build (src/offline-sw.ts). */
const PREFIX = "pura-stable-";
const CACHE = PREFIX + "d5636267f962";
const CORE = ["apple-touch-icon.png","assets/BenchPlay-DDn4daqm.js","assets/CurlingPlay-BXUrEUcK.js","assets/DropletLab-CylDlI1v.js","assets/EndlessPlay-C93buw0I.js","assets/FinaleLab-B9gSYN3O.js","assets/FreePlay-B574W-zO.js","assets/FusionLab-BX1mo9Go.js","assets/HitofudePlay-Chu-rH4H.js","assets/MakerPlay-DeHpxS3k.js","assets/MichiPlay-Cw9zoFqB.js","assets/OpenPlay-SyLvfzYi.js","assets/PurityScene-C2-B9BcC.js","assets/StagePlay-DjgF2WKk.js","assets/WelcomePlay-CNnXBu_8.js","assets/arrow-up-right-C78iXqDO.js","assets/boards-C_93EQX_.js","assets/chapters-CPimLJzO.js","assets/clear-glow-leITxlJj.js","assets/droplet-lab-YQvlIeZt.js","assets/game-app-9WQPqPS_.js","assets/ghost-touch-CcAN2iPF.js","assets/hitofude-CDYjLWLW.js","assets/index-DDwPEXTk.js","assets/intro-line-CvYk0VGh.js","assets/look-picker-DtPRmc5J.js","assets/mode-gallery-DoXL5r6t.js","assets/pause-aQcPx7_x.js","assets/phone-play-DBh08zpV.js","assets/play-DxLfXGlz.js","assets/renderer-B36N3tyt.js","assets/rotate-ccw-Dh-jpoR0.js","assets/send-CgV6j61l.js","assets/sim-ClW-iOED.js","assets/simulation-ChO2xmX6.js","assets/simulation-D3Jj_vUD.js","assets/simulation-DZ260XuP.js","assets/simulation-DnjLhpgd.js","assets/simulation-xxD4MSaQ.js","assets/sliders-horizontal-CVgEg3-j.js","assets/sound-nudge-CN4HUuVV.js","assets/sound-settings-CmkOuCDy.js","assets/style-BT2K6MiB.css","assets/undo-2-BT2X1hpF.js","assets/useSensoryFeedback-ic1rocuB.js","assets/volume-x-BsVYMj9t.js","assets/walls-C-GRO3-H.js","assets/white-finale-DKvrukLN.js","assets/x-CvXKIJ5w.js","favicon.svg","icon-192.png","icon-512.png","icon-maskable-512.png","index.html","manifest.webmanifest"];
const OPTIONAL = ["audio/the-white-basin-v1.m4a"];
const scope = () => new URL(self.registration.scope);
const here = u => new URL(u, self.registration.scope).href;

self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // Fresh copies (never the browser's old ones); one failure fails the install, which retries later.
    await Promise.all(CORE.map(async name => {
      const response = await fetch(new Request(here(name), { cache: 'reload' }));
      if (!response.ok) throw new Error('precache ' + name + ' ' + response.status);
      await cache.put(here(name), response);
    }));
    await Promise.all(OPTIONAL.map(name => fetch(new Request(here(name), { cache: 'reload' })).then(r => (r.ok ? cache.put(here(name), r) : undefined)).catch(() => undefined)));
  })());
});

self.addEventListener('activate', event => {
  // Only this channel's older caches; the other channel's are not ours.
  event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k => k.startsWith(PREFIX) && k !== CACHE).map(k => caches.delete(k)))));
});

// The page asks the waiting worker to take over, right after launch (offline-client.ts).
self.addEventListener('message', event => { if (event.data === 'skip') self.skipWaiting(); });

self.addEventListener('fetch', event => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url), base = scope();
  if (url.origin !== base.origin || !url.pathname.startsWith(base.pathname)) return;
  const rel = url.pathname.slice(base.pathname.length);
  // The stable worker's scope also covers /next/; the trial is not its business.
  if (rel.startsWith('next/') && !base.pathname.endsWith('/next/')) return;
  if (rel === 'sw.js' || rel === 'build-info.json') return;
  if (request.mode === 'navigate') {
    // The app picks its screen from the query, so every page is the one index.
    event.respondWith(caches.open(CACHE).then(cache => cache.match(here('index.html'))).then(hit => hit || fetch(request)));
    return;
  }
  event.respondWith(caches.open(CACHE).then(cache => cache.match(request.url)).then(hit => hit || fetch(request)));
});
