/* PURA offline worker pura-stable-8b8cc309e515 — generated by the build (src/offline-sw.ts). */
const PREFIX = "pura-stable-";
const CACHE = PREFIX + "8b8cc309e515";
const CORE = ["apple-touch-icon.png","assets/BenchPlay-DaimNSMD.js","assets/CurlingPlay-Ezf_zY5s.js","assets/DropletLab-vluzXeRI.js","assets/EndlessPlay-DPkcRk7F.js","assets/FreePlay-C28qZ0aF.js","assets/FusionLab-CdhWiL5T.js","assets/HitofudePlay-vsouAvU1.js","assets/MakerPlay-Ctisfk9J.js","assets/MichiPlay-CdA-y2lk.js","assets/OpenPlay-voOD2ukS.js","assets/PurityScene-DDbdGqLi.js","assets/StagePlay-SaRceL9l.js","assets/WelcomePlay-D_sp7ziV.js","assets/arrow-up-right-864kQQtp.js","assets/boards-C_93EQX_.js","assets/chapters-CPimLJzO.js","assets/clear-glow-D61QnZNu.js","assets/droplet-lab-YQvlIeZt.js","assets/game-app-C3W7Pf9a.js","assets/ghost-touch-BYep45j4.js","assets/hitofude-Bfi7A_Wr.js","assets/index-DSdVG5ZV.js","assets/intro-line-DzyVUBRL.js","assets/look-picker-DRq4AAuX.js","assets/pause-BOYCtttF.js","assets/phone-play-B5muEGaZ.js","assets/phone-play-R8N3CEv5.js","assets/play-CcZbq5cg.js","assets/renderer-B36N3tyt.js","assets/rotate-ccw-BSVJ6HHu.js","assets/send-C-RMf2sT.js","assets/sim-ClW-iOED.js","assets/simulation-D3Jj_vUD.js","assets/simulation-DZ260XuP.js","assets/simulation-DnjLhpgd.js","assets/simulation-u4D3fth5.js","assets/simulation-xxD4MSaQ.js","assets/sliders-horizontal-BxCSiaiP.js","assets/sound-nudge-DnwcH0vq.js","assets/sound-settings-C47tRHTz.js","assets/style-xT0uucxS.css","assets/undo-2-DXXDwdRE.js","assets/useSensoryFeedback-xjoVjdBX.js","assets/volume-x-DEDL78jl.js","assets/walls-g1UTnZVJ.js","assets/x-D3lxBGoX.js","favicon.svg","icon-192.png","icon-512.png","icon-maskable-512.png","index.html","manifest.webmanifest"];
const OPTIONAL = ["audio/the-white-basin-v1.m4a"];
const scope = () => new URL(self.registration.scope);
const here = u => new URL(u, self.registration.scope).href;

self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // Fresh copies (never the browser's old ones); one failure fails the install, which retries later.
    await Promise.all(CORE.map(async name => {
      const response = await fetch(new Request(here(name), { cache: 'reload' }));
      if (!response.ok) throw new Error('precache ' + name + ' ' + response.status);
      await cache.put(here(name), response);
    }));
    await Promise.all(OPTIONAL.map(name => fetch(new Request(here(name), { cache: 'reload' })).then(r => (r.ok ? cache.put(here(name), r) : undefined)).catch(() => undefined)));
  })());
});

self.addEventListener('activate', event => {
  // Only this channel's older caches; the other channel's are not ours.
  event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k => k.startsWith(PREFIX) && k !== CACHE).map(k => caches.delete(k)))));
});

// The page asks the waiting worker to take over, right after launch (offline-client.ts).
self.addEventListener('message', event => { if (event.data === 'skip') self.skipWaiting(); });

self.addEventListener('fetch', event => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url), base = scope();
  if (url.origin !== base.origin || !url.pathname.startsWith(base.pathname)) return;
  const rel = url.pathname.slice(base.pathname.length);
  // The stable worker's scope also covers /next/; the trial is not its business.
  if (rel.startsWith('next/') && !base.pathname.endsWith('/next/')) return;
  if (rel === 'sw.js' || rel === 'build-info.json') return;
  if (request.mode === 'navigate') {
    // The app picks its screen from the query, so every page is the one index.
    event.respondWith(caches.open(CACHE).then(cache => cache.match(here('index.html'))).then(hit => hit || fetch(request)));
    return;
  }
  event.respondWith(caches.open(CACHE).then(cache => cache.match(request.url)).then(hit => hit || fetch(request)));
});
