/* PURA offline worker pura-next-0645f51555ed — generated by the build (src/offline-sw.ts). */
const PREFIX = "pura-next-";
const CACHE = PREFIX + "0645f51555ed";
const CORE = ["apple-touch-icon.png","assets/BenchPlay-BJ9qxhk8.js","assets/CurlingPlay-DiMPVL6q.js","assets/DropletLab-CYXx5QXz.js","assets/EndlessPlay-C0LpezlG.js","assets/FreePlay-NOSy596x.js","assets/FusionLab-DQewqnBR.js","assets/HitofudePlay-AGTRbN1v.js","assets/MakerPlay-DdheUTX6.js","assets/MichiPlay-BkHQl7Xr.js","assets/OpenPlay-BKOzXKVf.js","assets/PurityScene-D3ZntA_M.js","assets/StagePlay-CDAy4AZJ.js","assets/WelcomePlay-DVq5YQIU.js","assets/arrow-up-right-CQddqOyf.js","assets/boards-C_93EQX_.js","assets/chapters-CPimLJzO.js","assets/clear-glow-uUF2RGLr.js","assets/droplet-lab-YQvlIeZt.js","assets/game-app-BUzHzgC8.js","assets/ghost-touch-Br0ywmcg.js","assets/hitofude-DYX98FEe.js","assets/index-Bm804fbv.js","assets/intro-line-BkV7yGIR.js","assets/look-picker-Cix4R-nd.js","assets/pause-DyhqCBAk.js","assets/phone-play-DVNwT5Ts.js","assets/phone-play-Deetm_FG.js","assets/play-CqFJLmrg.js","assets/renderer-B36N3tyt.js","assets/rotate-ccw-CF19cnu5.js","assets/send-B8DUkAat.js","assets/sim-ClW-iOED.js","assets/simulation-ChO2xmX6.js","assets/simulation-D3Jj_vUD.js","assets/simulation-DZ260XuP.js","assets/simulation-DnjLhpgd.js","assets/simulation-xxD4MSaQ.js","assets/sliders-horizontal-DpDP2HQd.js","assets/sound-nudge-BuHMUiDU.js","assets/sound-settings-BSFwRnz9.js","assets/style-DZHTfvbj.css","assets/undo-2-BVsgknJ3.js","assets/useSensoryFeedback-B-ug7L7k.js","assets/volume-x-C27KoXp4.js","assets/walls-BOM5z_yD.js","assets/x-C8BqKiKL.js","favicon.svg","icon-192.png","icon-512.png","icon-maskable-512.png","index.html","manifest.webmanifest"];
const OPTIONAL = ["audio/the-white-basin-v1.m4a"];
const scope = () => new URL(self.registration.scope);
const here = u => new URL(u, self.registration.scope).href;

self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // Fresh copies (never the browser's old ones); one failure fails the install, which retries later.
    await Promise.all(CORE.map(async name => {
      const response = await fetch(new Request(here(name), { cache: 'reload' }));
      if (!response.ok) throw new Error('precache ' + name + ' ' + response.status);
      await cache.put(here(name), response);
    }));
    await Promise.all(OPTIONAL.map(name => fetch(new Request(here(name), { cache: 'reload' })).then(r => (r.ok ? cache.put(here(name), r) : undefined)).catch(() => undefined)));
  })());
});

self.addEventListener('activate', event => {
  // Only this channel's older caches; the other channel's are not ours.
  event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k => k.startsWith(PREFIX) && k !== CACHE).map(k => caches.delete(k)))));
});

// The page asks the waiting worker to take over, right after launch (offline-client.ts).
self.addEventListener('message', event => { if (event.data === 'skip') self.skipWaiting(); });

self.addEventListener('fetch', event => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url), base = scope();
  if (url.origin !== base.origin || !url.pathname.startsWith(base.pathname)) return;
  const rel = url.pathname.slice(base.pathname.length);
  // The stable worker's scope also covers /next/; the trial is not its business.
  if (rel.startsWith('next/') && !base.pathname.endsWith('/next/')) return;
  if (rel === 'sw.js' || rel === 'build-info.json') return;
  if (request.mode === 'navigate') {
    // The app picks its screen from the query, so every page is the one index.
    event.respondWith(caches.open(CACHE).then(cache => cache.match(here('index.html'))).then(hit => hit || fetch(request)));
    return;
  }
  event.respondWith(caches.open(CACHE).then(cache => cache.match(request.url)).then(hit => hit || fetch(request)));
});
