/* PURA offline worker pura-next-d0f1f8c22b6b — generated by the build (src/offline-sw.ts). */
const PREFIX = "pura-next-";
const CACHE = PREFIX + "d0f1f8c22b6b";
const CORE = ["apple-touch-icon.png","assets/BenchPlay-iT01Voyc.js","assets/CurlingPlay-CA1DEOwW.js","assets/DropletLab-C-sJ7SGl.js","assets/EndlessPlay-QQBva2MG.js","assets/FinaleLab-CDxRiicX.js","assets/FreePlay-qCes0J0Z.js","assets/FusionLab-CCxGLHcw.js","assets/HitofudePlay-C70ibd6h.js","assets/MakerPlay-B85Oq4E-.js","assets/MichiPlay-DBCNgJAf.js","assets/OpenPlay-CmkSPA8U.js","assets/PurityScene-CL18PKUs.js","assets/StagePlay-Df3VpagL.js","assets/WelcomePlay-DX8swj1z.js","assets/arrow-up-right-Bn3jF3yL.js","assets/boards-C_93EQX_.js","assets/chapters-CPimLJzO.js","assets/clear-glow-B8CwQSz2.js","assets/droplet-lab-YQvlIeZt.js","assets/game-app-CQ6-L85U.js","assets/ghost-touch-BWuuJCY8.js","assets/hitofude-DDEO1hRj.js","assets/index-BJ50UlJC.js","assets/intro-line-Cw3Gjv1c.js","assets/look-picker-B8ly-5Il.js","assets/mode-gallery-DTPnACp3.js","assets/pause-BmKJ-Azf.js","assets/phone-play-CjwcFfBn.js","assets/play-B5lf0nYL.js","assets/renderer-B36N3tyt.js","assets/rotate-ccw-vwuhzKY4.js","assets/send-BmnUQcrn.js","assets/sim-ClW-iOED.js","assets/simulation-ChO2xmX6.js","assets/simulation-D3Jj_vUD.js","assets/simulation-DZ260XuP.js","assets/simulation-DnjLhpgd.js","assets/simulation-xxD4MSaQ.js","assets/sliders-horizontal-Bdl5aqWN.js","assets/sound-nudge-DaetG817.js","assets/sound-settings-EQ_nh8v1.js","assets/style-BT2K6MiB.css","assets/undo-2-eUOMihy_.js","assets/useSensoryFeedback-DfLLFdVj.js","assets/volume-x-BRt7T9iW.js","assets/walls-CTNsqggp.js","assets/white-finale-CPf1DV-2.js","assets/x-BtpTCtYg.js","favicon.svg","icon-192.png","icon-512.png","icon-maskable-512.png","index.html","manifest.webmanifest"];
const OPTIONAL = ["audio/the-white-basin-v1.m4a"];
const scope = () => new URL(self.registration.scope);
const here = u => new URL(u, self.registration.scope).href;

self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // Fresh copies (never the browser's old ones); one failure fails the install, which retries later.
    await Promise.all(CORE.map(async name => {
      const response = await fetch(new Request(here(name), { cache: 'reload' }));
      if (!response.ok) throw new Error('precache ' + name + ' ' + response.status);
      await cache.put(here(name), response);
    }));
    await Promise.all(OPTIONAL.map(name => fetch(new Request(here(name), { cache: 'reload' })).then(r => (r.ok ? cache.put(here(name), r) : undefined)).catch(() => undefined)));
  })());
});

self.addEventListener('activate', event => {
  // Only this channel's older caches; the other channel's are not ours.
  event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k => k.startsWith(PREFIX) && k !== CACHE).map(k => caches.delete(k)))));
});

// The page asks the waiting worker to take over, right after launch (offline-client.ts).
self.addEventListener('message', event => { if (event.data === 'skip') self.skipWaiting(); });

self.addEventListener('fetch', event => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url), base = scope();
  if (url.origin !== base.origin || !url.pathname.startsWith(base.pathname)) return;
  const rel = url.pathname.slice(base.pathname.length);
  // The stable worker's scope also covers /next/; the trial is not its business.
  if (rel.startsWith('next/') && !base.pathname.endsWith('/next/')) return;
  if (rel === 'sw.js' || rel === 'build-info.json') return;
  if (request.mode === 'navigate') {
    // The app picks its screen from the query, so every page is the one index.
    event.respondWith(caches.open(CACHE).then(cache => cache.match(here('index.html'))).then(hit => hit || fetch(request)));
    return;
  }
  event.respondWith(caches.open(CACHE).then(cache => cache.match(request.url)).then(hit => hit || fetch(request)));
});
