/* PURA offline worker pura-next-eec301c579a8 — generated by the build (src/offline-sw.ts). */
const PREFIX = "pura-next-";
const CACHE = PREFIX + "eec301c579a8";
const CORE = ["apple-touch-icon.png","assets/BenchPlay-BhTxsq6r.js","assets/CurlingPlay-q_4rkjUZ.js","assets/DropletLab-CRhPAWBq.js","assets/EndlessPlay-DXNlzfqt.js","assets/FreePlay-XJqmkPRW.js","assets/FusionLab-Dsd-r8TE.js","assets/HitofudePlay-C_eebxzM.js","assets/MakerPlay-BIbwUZ3-.js","assets/MichiPlay-DxQPdXQp.js","assets/OpenPlay-C0i77iYT.js","assets/PurityScene-BpZlG8fY.js","assets/StagePlay-mUtYiMpl.js","assets/WelcomePlay-Cr2-KxUe.js","assets/arrow-up-right-7Skmvp5P.js","assets/boards-C_93EQX_.js","assets/chapters-CPimLJzO.js","assets/clear-glow-B6w2i0ZK.js","assets/droplet-lab-YQvlIeZt.js","assets/game-app-Dv1xiZIM.js","assets/ghost-touch-Cls3f5cF.js","assets/hitofude-B_hhQRCb.js","assets/index-BnJK_XQJ.js","assets/intro-line-z0jnL-vs.js","assets/look-picker-qOwVth_B.js","assets/pause-D_AA-5c0.js","assets/phone-play-BeeVkBqO.js","assets/phone-play-cIQGkb1W.js","assets/play-Dybafewc.js","assets/renderer-B36N3tyt.js","assets/rotate-ccw-DRt9XwuS.js","assets/send-D3YwPWAm.js","assets/sim-ClW-iOED.js","assets/simulation-D3Jj_vUD.js","assets/simulation-DZ260XuP.js","assets/simulation-DnjLhpgd.js","assets/simulation-u4D3fth5.js","assets/simulation-xxD4MSaQ.js","assets/sliders-horizontal-X0uC-_Ud.js","assets/sound-nudge-DCrLs1Bt.js","assets/sound-settings-5_QRHgte.js","assets/style-xT0uucxS.css","assets/undo-2-DLz-iKia.js","assets/useSensoryFeedback-C407OkkF.js","assets/volume-x-Dy00V7Aa.js","assets/walls--Xx-DMfv.js","assets/x-IXhrzuGz.js","favicon.svg","icon-192.png","icon-512.png","icon-maskable-512.png","index.html","manifest.webmanifest"];
const OPTIONAL = ["audio/the-white-basin-v1.m4a"];
const scope = () => new URL(self.registration.scope);
const here = u => new URL(u, self.registration.scope).href;

self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // Fresh copies (never the browser's old ones); one failure fails the install, which retries later.
    await Promise.all(CORE.map(async name => {
      const response = await fetch(new Request(here(name), { cache: 'reload' }));
      if (!response.ok) throw new Error('precache ' + name + ' ' + response.status);
      await cache.put(here(name), response);
    }));
    await Promise.all(OPTIONAL.map(name => fetch(new Request(here(name), { cache: 'reload' })).then(r => (r.ok ? cache.put(here(name), r) : undefined)).catch(() => undefined)));
  })());
});

self.addEventListener('activate', event => {
  // Only this channel's older caches; the other channel's are not ours.
  event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k => k.startsWith(PREFIX) && k !== CACHE).map(k => caches.delete(k)))));
});

// The page asks the waiting worker to take over, right after launch (offline-client.ts).
self.addEventListener('message', event => { if (event.data === 'skip') self.skipWaiting(); });

self.addEventListener('fetch', event => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url), base = scope();
  if (url.origin !== base.origin || !url.pathname.startsWith(base.pathname)) return;
  const rel = url.pathname.slice(base.pathname.length);
  // The stable worker's scope also covers /next/; the trial is not its business.
  if (rel.startsWith('next/') && !base.pathname.endsWith('/next/')) return;
  if (rel === 'sw.js' || rel === 'build-info.json') return;
  if (request.mode === 'navigate') {
    // The app picks its screen from the query, so every page is the one index.
    event.respondWith(caches.open(CACHE).then(cache => cache.match(here('index.html'))).then(hit => hit || fetch(request)));
    return;
  }
  event.respondWith(caches.open(CACHE).then(cache => cache.match(request.url)).then(hit => hit || fetch(request)));
});
