/**
 * Offline play (2026-10-02, RYO: play without a connection). The build writes a
 * service worker that keeps the whole game on the device. Pure functions, so
 * Node tests and the Vite plugin (vite.config.ts) can use them.
 *
 * Rules that keep it safe:
 * - The cache is named by a hash of every file, so a new deploy is a new cache.
 * - A new worker waits; the page swaps to it only right after launch, before
 *   any touch (offline-client.ts), so a running game is never replaced.
 * - Stable and trial (/next/) use different cache names and each worker leaves
 *   the other's addresses alone.
 * - build-info.json and sw.js always come from the network.
 */
export type CacheEntry = { name: string; hash: string };

/** Files that are not worth keeping: the preview image, the worker itself, deploy notes. */
export const NEVER_CACHED = [/^sw\.js$/, /^build-info\.json$/, /^og\.jpg$/, /\.map$/];
/** Kept after the game itself, and allowed to fail without blocking the install (the music). */
export const OPTIONAL = [/^audio\//];

export function precacheLists(names: string[]) {
  const kept = names.filter(n => !NEVER_CACHED.some(r => r.test(n))).sort();
  return { core: kept.filter(n => !OPTIONAL.some(r => r.test(n))), optional: kept.filter(n => OPTIONAL.some(r => r.test(n))) };
}

/** A short version that changes when any kept file's name or content changes, whatever the order given. */
export function cacheVersion(entries: CacheEntry[], hashOf: (text: string) => string) {
  const kept = entries.filter(e => !NEVER_CACHED.some(r => r.test(e.name))).sort((a, b) => (a.name < b.name ? -1 : 1));
  return hashOf(kept.map(e => `${e.name}:${e.hash}`).join('\n')).slice(0, 12);
}

export function cachePrefix(channel: string | undefined) { return channel === 'next' ? 'pura-next-' : 'pura-stable-'; }

/** The worker's source, with the file lists and version filled in. */
export function serviceWorkerSource({ prefix, version, core, optional }: { prefix: string; version: string; core: string[]; optional: string[] }) {
  return `/* PURA offline worker ${prefix}${version} — generated by the build (src/offline-sw.ts). */
const PREFIX = ${JSON.stringify(prefix)};
const CACHE = PREFIX + ${JSON.stringify(version)};
const CORE = ${JSON.stringify(core)};
const OPTIONAL = ${JSON.stringify(optional)};
const scope = () => new URL(self.registration.scope);
const here = u => new URL(u, self.registration.scope).href;

self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // Fresh copies (never the browser's old ones); one failure fails the install, which retries later.
    await Promise.all(CORE.map(async name => {
      const response = await fetch(new Request(here(name), { cache: 'reload' }));
      if (!response.ok) throw new Error('precache ' + name + ' ' + response.status);
      await cache.put(here(name), response);
    }));
    await Promise.all(OPTIONAL.map(name => fetch(new Request(here(name), { cache: 'reload' })).then(r => (r.ok ? cache.put(here(name), r) : undefined)).catch(() => undefined)));
  })());
});

self.addEventListener('activate', event => {
  // Only this channel's older caches; the other channel's are not ours.
  event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k => k.startsWith(PREFIX) && k !== CACHE).map(k => caches.delete(k)))));
});

// The page asks the waiting worker to take over, right after launch (offline-client.ts).
self.addEventListener('message', event => { if (event.data === 'skip') self.skipWaiting(); });

self.addEventListener('fetch', event => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url), base = scope();
  if (url.origin !== base.origin || !url.pathname.startsWith(base.pathname)) return;
  const rel = url.pathname.slice(base.pathname.length);
  // The stable worker's scope also covers /next/; the trial is not its business.
  if (rel.startsWith('next/') && !base.pathname.endsWith('/next/')) return;
  if (rel === 'sw.js' || rel === 'build-info.json') return;
  if (request.mode === 'navigate') {
    // The app picks its screen from the query, so every page is the one index.
    event.respondWith(caches.open(CACHE).then(cache => cache.match(here('index.html'))).then(hit => hit || fetch(request)));
    return;
  }
  event.respondWith(caches.open(CACHE).then(cache => cache.match(request.url)).then(hit => hit || fetch(request)));
});
`;
}

/** Swap to a waiting worker only right after launch and before any touch. */
export const SWAP_WINDOW_MS = 12000;
export function shouldSwap(state: { hasWaiting: boolean; hasController: boolean; sinceLaunchMs: number; touched: boolean }) {
  return state.hasWaiting && state.hasController && !state.touched && state.sinceLaunchMs < SWAP_WINDOW_MS;
}
